import assert from 'node:assert/strict'
import {
  cssSource,
  inTransitBatchListSource,
  tabSource
} from './replenishmentPlanContractSources'

assert.doesNotMatch(tabSource, /title:\s*['"]销量依据['"]/, 'ReplenishmentPlanTab must split sales evidence into history and forecast columns')
assert.match(tabSource, /Tooltip[\s\S]*校正历史[\s\S]*ExclamationCircleOutlined[\s\S]*历史数据说明/, 'history table title must expose a small exclamation tooltip with detailed explanation')
assert.match(tabSource, /title:\s*\([\s\S]*历史数据[\s\S]*Tooltip[\s\S]*dataIndex:\s*['"]historyUnits7['"]/, 'ReplenishmentPlanTab must show historical evidence in its own column')
assert.match(tabSource, /dataIndex:\s*['"]historyUnits7['"][\s\S]*width:\s*['"]20%['"]/, 'history evidence column must be narrower after shortening the segmented history header')
assert.match(tabSource, /title:\s*['"]预测数据['"][\s\S]*dataIndex:\s*['"]forecastUnits100['"]/, 'ReplenishmentPlanTab must show forecast evidence in its own column')
assert.match(tabSource, /dataIndex:\s*['"]forecastUnits100['"][\s\S]*width:\s*['"]18%['"]/, 'forecast evidence column must be wider for aligned prediction rows')
assert.match(tabSource, /dataIndex:\s*['"]knownInboundUnits['"][\s\S]*width:\s*['"]23%['"]/, 'inbound evidence column must be wider for aligned batch rows')
assert.doesNotMatch(tabSource, /scroll=\{\{\s*x:/, 'ReplenishmentPlanTab must not require horizontal table scrolling')
assert.doesNotMatch(tabSource, /title:\s*['"]库存依据['"]/, 'ReplenishmentPlanTab must not show inventory evidence as a separate table column')
assert.match(tabSource, /replenishment-plan-product-stock/, 'ReplenishmentPlanTab must show inventory evidence under product information')
assert.match(tabSource, /FBN\s*\{formatQuantity\(item\.fbnStockUnits\)\}/, 'ReplenishmentPlanTab inventory evidence must show FBN stock')
assert.match(tabSource, /Supermall\s*\{formatQuantity\(item\.supermallStockUnits\)\}/, 'ReplenishmentPlanTab inventory evidence must display Supermall stock')
assert.doesNotMatch(tabSource, /Supermall[\s\S]*不计入/, 'ReplenishmentPlanTab must not show the Supermall exclusion copy in the compact product cell')
assert.doesNotMatch(tabSource, /合计\s*\{formatQuantity\(item\.currentStockUnits\)\}/, 'ReplenishmentPlanTab inventory evidence must not show FBN+Supermall totals')
assert.match(tabSource, /上架[\s\S]*formatDate\(item\.listingAt\)[\s\S]*formatListingAgeDays\(item\.listingAt,\s*planDate\)/, 'ReplenishmentPlanTab must show listing date and age days under product information')
assert.match(tabSource, /function formatListingAgeDays/, 'ReplenishmentPlanTab must calculate listing age days locally from the plan date')
assert.match(tabSource, /onImageClick=\{item\.imageUrl \? \(\) => setPreviewImage/, 'ReplenishmentPlanTab product image must be clickable for full-size preview')
assert.match(tabSource, /<Modal[\s\S]*open=\{Boolean\(previewImage\)\}[\s\S]*<img[\s\S]*src=\{previewImage\.url\}/, 'ReplenishmentPlanTab must render a full-size image preview modal')
assert.match(tabSource, /formatMonthDay/, 'ReplenishmentPlanTab must show inbound ETA as month-day in list rows')
assert.match(tabSource, /SEA|AIR/, 'ReplenishmentPlanTab must map sea and air suggestions to transport modes')
assert.match(tabSource, /未来100天/, 'ReplenishmentPlanTab must label the forecast evidence as future 100 days')
assert.match(tabSource, /forecastUnits100/, 'ReplenishmentPlanTab must show the future 100-day forecast evidence in the list')
assert.doesNotMatch(tabSource, /\{item\.forecastUnits30\}\s*\/\s*\{item\.forecastUnits60\}\s*\/\s*\{item\.forecastUnits90\}/, 'ReplenishmentPlanTab must not show the old 30/60/90 forecast summary as the main replenishment forecast evidence')
assert.match(tabSource, /summarizeMissingEta/, 'ReplenishmentPlanTab must summarize missing ETA logistics facts')
assert.match(tabSource, /replenishment-plan-missing-eta-alert/, 'ReplenishmentPlanTab must show the missing ETA maintenance alert')
assert.match(tabSource, /openMissingEtaOverviewMaintenance/, 'missing ETA alert must navigate to in-transit maintenance')
assert.match(tabSource, /calculationBlocked/, 'ReplenishmentPlanTab must render and enforce the backend calculation blocked state')
assert.match(tabSource, /getCheckboxProps/, 'blocked rows must not be selectable for batch purchase')
assert.doesNotMatch(tabSource, /title:\s*['"]数据依据['"]/, 'ReplenishmentPlanTab must not restore the old 数据依据 column label')
assert.match(tabSource, /实际历史[\s\S]*item\.observedDays[\s\S]*item\.confidenceLabel[\s\S]*稳定[\s\S]*formatMonthlyStabilityFactor\(item\)/, 'ReplenishmentPlanTab must show monthly stability after observed days and confidence')
assert.match(tabSource, /replenishment-plan-history-row/, 'historical evidence rows must use a dedicated aligned row class')
const historyRowCssBlock = cssSource.match(/\.replenishment-plan-history-row \{[\s\S]*?\}/)?.[0] || ''
assert.match(historyRowCssBlock, /display:\s*grid/, 'historical evidence rows must use grid alignment')
assert.match(historyRowCssBlock, /grid-template-columns:\s*64px\s+minmax\(0,\s*1fr\)/, 'historical evidence labels and values must share fixed aligned columns')
assert.match(tabSource, /历史时间[\s\S]*7 \/ 30 \/ 30-60 \/ 60-90天/, 'ReplenishmentPlanTab must use a compact historical window label')
assert.match(tabSource, /校正历史[\s\S]*formatAdjustedHistoryBuckets\(item\)/, 'ReplenishmentPlanTab must show adjusted history as recent and segmented buckets')
assert.doesNotMatch(tabSource, /补全历史/, 'ReplenishmentPlanTab must not call calendar-adjusted history 补全历史')
assert.match(tabSource, /原始历史[\s\S]*formatRawHistoryBuckets\(item\)/, 'ReplenishmentPlanTab must keep raw history as recent and segmented comparison evidence')
assert.match(tabSource, /function formatWholeQuantity[\s\S]*Math\.round/, 'ReplenishmentPlanTab must round imputed history evidence to integer units')
assert.match(tabSource, /function formatAdjustedHistoryBuckets[\s\S]*historyBuckets\([\s\S]*adjustedHistoryUnits7[\s\S]*adjustedHistoryUnits30[\s\S]*adjustedHistoryUnits60[\s\S]*adjustedHistoryUnits90/, 'adjusted history buckets must derive from 7/30/60/90 adjusted histories')
assert.match(tabSource, /function formatRawHistoryBuckets[\s\S]*historyBuckets\([\s\S]*historyUnits7[\s\S]*historyUnits30[\s\S]*historyUnits60[\s\S]*historyUnits90/, 'raw history buckets must derive from 7/30/60/90 raw histories')
assert.match(tabSource, /function historyBuckets[\s\S]*history60 - history30[\s\S]*history90 - history60/, 'history buckets must split 30-60 and 60-90 instead of showing cumulative 60/90')
assert.doesNotMatch(tabSource, /formatWholeQuantity\(item\.adjustedHistoryUnits60\)[\s\S]*formatWholeQuantity\(item\.adjustedHistoryUnits90\)/, 'adjusted history display must not show cumulative 60/90 quantities')
assert.doesNotMatch(tabSource, /月稳定/, 'monthly stability must not take a separate historical evidence row')
assert.doesNotMatch(tabSource, /近3月/, 'monthly stability buckets must not be displayed as a separate row')
assert.doesNotMatch(tabSource, /formatMonthlySalesBuckets/, 'monthly stability buckets must not keep a display formatter when the row is hidden')
assert.match(tabSource, /function monthlySalesBuckets[\s\S]*adjustedHistoryUnits30[\s\S]*adjustedHistoryUnits60[\s\S]*adjustedHistoryUnits90/, 'monthly stability must derive from the latest three 30-day adjusted sales windows')
assert.match(tabSource, /function monthlyStabilityFactor[\s\S]*Math\.sqrt[\s\S]*average/, 'monthly stability factor must measure variance against the three-month average')
assert.match(tabSource, /function formatMonthlyStabilityFactor[\s\S]*factor\.toFixed\(2\)/, 'monthly stability factor must be displayed as a decimal such as 0.49')
assert.doesNotMatch(tabSource, /\$\{factor\}%/, 'monthly stability factor must not be displayed as a percentage')
assert.match(tabSource, /Math\.min\(1[\s\S]*1 - coefficientOfVariation/, 'monthly stability factor must be normalized to a 0-1 decimal')
assert.doesNotMatch(tabSource, /\*\s*100/, 'monthly stability factor must not multiply the normalized value into a percentage')
const historyWindowLabelIndex = tabSource.indexOf('7 / 30 / 30-60 / 60-90天')
const historyQuantityLabelIndex = tabSource.indexOf('formatRawHistoryBuckets(item)')
assert.ok(historyQuantityLabelIndex >= 0, 'ReplenishmentPlanTab must show historical sales quantities with 件')
assert.ok(
  historyWindowLabelIndex >= 0 && historyWindowLabelIndex < historyQuantityLabelIndex,
  'historical sales window label must render before quantity label'
)
assert.match(tabSource, /replenishment-plan-window-mode[\s\S]*空运[\s\S]*replenishment-plan-window-days[\s\S]*item\.airWindowStartDay[\s\S]*item\.airWindowEndDay[\s\S]*replenishment-plan-window-value[\s\S]*item\.airWindowForecastUnits/, 'air forecast window must split mode, days, and value into aligned cells')
assert.match(tabSource, /replenishment-plan-window-mode[\s\S]*海运[\s\S]*replenishment-plan-window-days[\s\S]*item\.seaWindowStartDay[\s\S]*item\.seaWindowEndDay[\s\S]*replenishment-plan-window-value[\s\S]*item\.seaWindowForecastUnits/, 'sea forecast window must split mode, days, and value into aligned cells')
assert.doesNotMatch(tabSource, /空运\s*\{item\.airWindowStartDay\}-\{item\.airWindowEndDay\}\s*天\s*预测/, 'air forecast window must not be rendered as one natural text sentence')
const forecastWindowCssBlock = cssSource.match(/\.replenishment-plan-window-line \{[\s\S]*?\}/)?.[0] || ''
assert.match(forecastWindowCssBlock, /display:\s*grid/, 'forecast window rows must use grid alignment')
assert.match(forecastWindowCssBlock, /grid-template-columns:\s*32px\s+84px\s+32px\s+max-content/, 'forecast window rows must align mode, days, label, and value columns')
assert.match(tabSource, /airWindowForecastUnits/, 'ReplenishmentPlanTab must show backend-provided air-window forecast units')
assert.match(tabSource, /seaWindowForecastUnits/, 'ReplenishmentPlanTab must show backend-provided sea-window forecast units')
assert.match(tabSource, /const label = isAir \? ['"]空运['"] : ['"]海运['"][\s\S]*const calculatedUnits = isAir \? item\.airCalculatedUnits : item\.seaCalculatedUnits[\s\S]*const suggestedUnits = isAir \? item\.airSuggestedUnits : item\.seaSuggestedUnits[\s\S]*计算 \{formatQuantity\(calculatedUnits\)\} \/ 建议 \{formatQuantity\(suggestedUnits\)\}/, 'ReplenishmentPlanTab must show both raw calculation and final suggestion for air and sea')
assert.doesNotMatch(tabSource, /预测销量/, 'ReplenishmentPlanTab must use concise 预测 wording for replenishment window forecasts')
assert.match(tabSource, /firstStockoutDay[\s\S]*第 \{item\.firstStockoutDay\} 天缺货/, 'ReplenishmentPlanTab must show stockout day in forecast evidence')
assert.match(tabSource, /etaReviewRequired/, 'ReplenishmentPlanTab must highlight recent past ETA batches that need review')
assert.match(tabSource, /待判断/, 'ReplenishmentPlanTab must label recent past ETA rows as needing manual judgment')
assert.match(tabSource, /item\.inboundBatches/, 'ReplenishmentPlanTab must render known ETA inbound batch list from API data')
assert.match(tabSource, /item\.missingEtaBatches/, 'ReplenishmentPlanTab must render missing ETA batch list from API data')
assert.match(tabSource, /replenishment-plan-inbound-summary/, 'inbound summary row must use the same aligned column system')
assert.match(tabSource, /renderInboundBatchGroup\(item\.inboundBatches,\s*['"]known['"],\s*planDate,\s*overview\?\.siteCode \|\| query\?\.siteCode \|\| ['"]['"]\)/, 'known inbound rows must use the page plan date and exact page site')
assert.match(tabSource, /formatEtaDistanceDays\(etaDate,\s*planDate\)/, 'inbound ETA rows must show distance from today after the date')
assert.match(tabSource, /batch\.destinationCode[\s\S]*batch\.destinationCode\} \/ \$\{siteCode/, 'inbound rows must display destination and site together')
assert.match(tabSource, /replenishment-plan-inbound-destination/, 'inbound destination must have a dedicated non-truncated display line')
assert.match(tabSource, /inbound_site_unresolved:\s*['"]在途目的站点无法确认['"]/, 'unresolved inbound destination must have a blocking user-facing label')
assert.match(tabSource, /replenishment-plan-inbound-eta/, 'inbound ETA date should have a dedicated emphasis class')
assert.match(tabSource, /replenishment-plan-inbound-quantity/, 'inbound quantity should have a weak display class')
const inboundBatchCssBlock = cssSource.match(/\.replenishment-plan-inbound-batch \{[\s\S]*?\}/)?.[0] || ''
assert.match(inboundBatchCssBlock, /width:\s*100%/, 'inbound batch rows should fill the cell so columns line up across rows')
assert.match(inboundBatchCssBlock, /grid-template-columns:\s*minmax\(118px,\s*1fr\)\s+44px\s+minmax\(92px,\s*max-content\)/, 'inbound batch rows must align batch reference, quantity, and ETA columns')
assert.match(inboundBatchCssBlock, /column-gap:\s*10px/, 'inbound batch rows should keep consistent column spacing')
const inboundRefCssBlock = cssSource.match(/\.replenishment-plan-inbound-ref \{[\s\S]*?\}/)?.[0] || ''
assert.match(inboundRefCssBlock, /max-width:\s*132px/, 'inbound batch reference should truncate before pushing quantity too far away')
assert.match(inboundRefCssBlock, /color:\s*#6b7280/, 'inbound batch reference should be visually weaker than ETA')
const inboundEtaCssBlock = cssSource.match(/\.replenishment-plan-inbound-eta \{[\s\S]*?\}/)?.[0] || ''
assert.match(inboundEtaCssBlock, /font-weight:\s*600/, 'inbound ETA date should be emphasized')
assert.doesNotMatch(tabSource, /item\.shortReason/, 'ReplenishmentPlanTab must not render the long persisted shortReason in list cells')
assert.match(tabSource, /imageUrl=\{item\.imageUrl\}/, 'ReplenishmentPlanTab must pass product image into the shared product identity component')
assert.match(tabSource, /imageWidth=\{72\}/, 'ReplenishmentPlanTab product image should be large enough for row scanning')
assert.match(tabSource, /replenishment-plan-product-codes/, 'ReplenishmentPlanTab must stack product codes in the product cell')
assert.match(tabSource, /copyable=\{\{ text: item\.partnerSku \}\}>\{item\.partnerSku\}<\/Text>/, 'product cell must show partner SKU value without a PSKU prefix')
assert.match(tabSource, /copyable=\{\{ text: item\.sku \}\}>\{item\.sku\}<\/Text>/, 'product cell must show SKU value without a SKU prefix')
assert.doesNotMatch(tabSource, />PSKU\s*\{item\.partnerSku\}/, 'product cell must not show the PSKU label prefix')
assert.doesNotMatch(tabSource, />SKU\s*\{item\.sku\}/, 'product cell must not show the SKU label prefix')
assert.match(tabSource, /replenishment-plan-product-meta[\s\S]*replenishment-plan-product-codes[\s\S]*replenishment-plan-product-stock/, 'product inventory must render under product codes')
const productCellCssBlock = cssSource.match(/\.replenishment-plan-product-cell \{[\s\S]*?\}/)?.[0] || ''
assert.doesNotMatch(productCellCssBlock, /grid-template-columns/, 'product cell must not reserve a right-side inventory block')
assert.doesNotMatch(tabSource, /showImage=\{false\}/, 'ReplenishmentPlanTab product column must show images like other product lists')
assert.doesNotMatch(tabSource, /Drawer/, 'ReplenishmentPlanTab must keep evidence in the list instead of a details drawer')
assert.doesNotMatch(tabSource, /fetchSalesForecastOverview|sales-data\/analytics|DailySalesFact/, 'ReplenishmentPlanTab must not re-run or fetch sales analytics evidence')

const inboundBatchGroupBlock = tabSource.match(/function renderInboundBatchGroup[\s\S]*?\n\}/)?.[0] || ''
assert.doesNotMatch(inboundBatchGroupBlock, /<Button|维护 ETA/, 'ReplenishmentPlanTab must not keep row-level ETA maintenance buttons')
assert.doesNotMatch(tabSource, /有 ETA 批次|缺 ETA 批次/, 'ReplenishmentPlanTab must not show inbound batch group labels in rows')

assert.match(inTransitBatchListSource, /statusScope/, 'in-transit list must support statusScope query param')
assert.match(inTransitBatchListSource, /skuKeyword/, 'in-transit list must support skuKeyword query param')
