import assert from 'node:assert/strict'
import {
  cssSource,
  purchaseDraftsSource,
  purchaseDuplicateNoticeSource,
  purchaseProgressSource,
  tabSource
} from './replenishmentPlanContractSources'

assert.match(tabSource, /loadPurchaseOrders/, 'ReplenishmentPlanTab must load existing purchase orders')
assert.match(tabSource, /addPurchaseOrderItems/, 'ReplenishmentPlanTab must reuse the existing add-items API')
assert.match(tabSource, /批量加入采购/, 'ReplenishmentPlanTab must support batch add to purchase order')
assert.match(tabSource, /加入采购/, 'ReplenishmentPlanTab must support single-row add to purchase order')
assert.match(tabSource, /InputNumber/, 'ReplenishmentPlanTab must allow manual quantity edits')
assert.match(tabSource, /Select/, 'ReplenishmentPlanTab must allow selecting an existing purchase order')
assert.match(tabSource, /dataIndex:\s*['"]partnerSku['"][\s\S]*width:\s*['"]22%['"]/, 'product column must stay compact after removing PSKU/SKU labels')
assert.match(tabSource, /suggestionFilter/, 'ReplenishmentPlanTab must expose a replenishment suggestion filter')
assert.doesNotMatch(tabSource, /需要补空运|需要补海运|全部建议/, 'ReplenishmentPlanTab must not keep the old standalone replenishment filter select')
assert.match(tabSource, /renderSuggestionFilterButton/, 'ReplenishmentPlanTab must use summary chips as replenishment filters')
assert.match(tabSource, /renderSuggestionFilterButton\(['"]all['"],\s*['"]全部['"],\s*suggestionSummary\.totalSkuCount,\s*['"]SKU['"]\)/, 'all summary chip must include products that do not need replenishment')
assert.match(tabSource, /renderSuggestionFilterButton\(['"]needed['"],\s*['"]需要补货['"],\s*suggestionSummary\.replenishmentSkuCount,\s*['"]SKU['"]\)/, 'needed summary chip must filter products that need replenishment')
assert.match(tabSource, /renderSuggestionFilterButton\(['"]air['"],\s*['"]空运['"],\s*suggestionSummary\.airSkuCount\)/, 'air summary chip must filter rows that need air replenishment')
assert.match(tabSource, /renderSuggestionFilterButton\(['"]sea['"],\s*['"]海运['"],\s*suggestionSummary\.seaSkuCount\)/, 'sea summary chip must filter rows that need sea replenishment')
assert.match(tabSource, /SEA_ETA_UNCERTAIN_AIR_WINDOW_WARNING\s*=\s*['"]sea_eta_uncertain_air_window_coverage['"]/, 'replenishment tab must read the backend sea ETA uncertainty warning')
assert.match(tabSource, /SEA_ETA_UNCERTAIN_AIR_WINDOW_TOOLTIP\s*=\s*['"]海运到货时间具有不确定性 谨慎评判['"]/, 'sea ETA uncertainty warning must use the agreed hover copy')
assert.match(tabSource, /const seaEtaRisk = isAir && hasSeaEtaRiskWarning\(item\)/, 'only the air suggestion tag should be marked risky when sea ETA affects air coverage')
assert.match(tabSource, /tagColor = seaEtaRisk \? ['"]red['"]/, 'sea ETA uncertainty must render the affected air suggestion tag in red')
assert.match(cssSource, /\.replenishment-plan-suggestion-tag\.is-sea-eta-risk/, 'sea ETA uncertainty tag styling must be durable in CSS')
assert.match(tabSource, /onClick=\{\(\) => setSuggestionFilter\(filter\)\}/, 'summary filter chips must update the active suggestion filter when clicked')
assert.match(tabSource, /aria-pressed=\{suggestionFilter === filter\}/, 'summary filter chips must expose active state')
assert.match(tabSource, /replenishment-plan-toolbar-actions[\s\S]*<Button[\s\S]*ReloadOutlined[\s\S]*刷新[\s\S]*批量加入采购/, 'refresh button must live in the right toolbar action area')
assert.match(tabSource, /summarizeSuggestions/, 'ReplenishmentPlanTab must summarize replenishment suggestions from the current list')
assert.match(tabSource, /const totalSkuCount = rows\.length/, 'suggestion summary total count must include non-replenishment rows')
assert.match(tabSource, /if \(suggestionFilter === ['"]needed['"]\)/, 'needed filter must be distinct from all rows')
assert.match(tabSource, /if \(suggestionFilter === ['"]all['"]\)[\s\S]*return true/, 'all filter must show every searched row')
assert.match(tabSource, /buildPurchaseDrafts/, 'ReplenishmentPlanTab must build purchase drafts from replenishment suggestions')
assert.match(tabSource, /const \[openingPurchaseKey,\s*setOpeningPurchaseKey\] = useState<string>\(\)/, 'single-row add must track loading by the clicked product row instead of a global boolean')
assert.match(tabSource, /purchaseOrdersRevision\?: number/, 'ReplenishmentPlanTab must accept purchase-order revision changes from the parent page')
assert.match(tabSource, /useEffect\(\(\) => \{\s*void loadEditablePurchaseOrders\(\)\s*\}, \[loadEditablePurchaseOrders,\s*purchaseOrdersRevision\]\)/, 'ReplenishmentPlanTab must reload purchase orders when the parent purchase-order revision changes')
assert.match(tabSource, /const openingKey = purchaseOpeningKey\(targetRows\)[\s\S]*setOpeningPurchaseKey\(openingKey\)[\s\S]*finally\s*\{\s*setOpeningPurchaseKey\(undefined\)\s*\}/, 'opening purchase modal must set and clear the row-specific loading key')
assert.match(tabSource, /function purchaseOpeningKey\(targetRows: ReplenishmentPlanItem\[\]\)[\s\S]*BATCH_PURCHASE_OPENING_KEY[\s\S]*targetRows\[0\]\?\.partnerSku/, 'single-row and batch loading keys must be distinct')
assert.match(tabSource, /onClick=\{\(\) => void openPurchaseModal\(\[item\]\)\}[\s\S]*loading=\{openingPurchaseKey === purchaseOpeningKey\(\[item\]\)\}/, 'single-row add button must only show loading for the clicked product')
assert.match(tabSource, /loading=\{openingPurchaseKey === BATCH_PURCHASE_OPENING_KEY\}[\s\S]*批量加入采购/, 'batch add button must use a separate loading key')
assert.match(tabSource, /const \[selectedPurchaseRows,\s*setSelectedPurchaseRows\] = useState<ReplenishmentPlanItem\[\]>\(\[\]\)/, 'batch add must store the actual selected row snapshot from the table selection callback')
assert.match(tabSource, /function handleSelectedRowsChange\(keys: Key\[\],\s*rows: ReplenishmentPlanItem\[\]\)[\s\S]*setSelectedRowKeys\(keys\)[\s\S]*setSelectedPurchaseRows\(rows\)/, 'table selection must keep selected keys and selected row snapshots together')
assert.match(tabSource, /disabled=\{!selectedPurchaseRows\.length\}[\s\S]*onClick=\{\(\) => void openPurchaseModal\(selectedPurchaseRows,\s*['"]batch['"]\)\}/, 'batch add button must open the modal from the selected row snapshot with batch filtering, not rows re-derived from the current filtered list')
assert.doesNotMatch(tabSource, /const selectedRows = selectedRowKeys[\s\S]*filteredRows\.find/, 'batch add must not reconstruct selected rows from filteredRows because pagination or refreshed filters can show the wrong products')
assert.match(tabSource, /const \[purchaseDuplicateNotice,\s*setPurchaseDuplicateNotice\] = useState\(['"]['"]\)/, 'duplicate purchase transport warning must use inline modal state so repeated add can warn without blocking')
assert.doesNotMatch(tabSource, /duplicateTransportWarning|setDuplicateTransportWarning|没有可新增的运输方式/, 'duplicate purchase feedback must no longer block the add flow with a separate modal')
assert.match(tabSource, /replenishment-plan-purchase-duplicate-alert[\s\S]*type=['"]error['"][\s\S]*purchaseDuplicateNotice/, 'duplicate purchase feedback must render as a red alert at the top of the add-purchase modal')
assert.doesNotMatch(tabSource, /Modal\.warning/, 'duplicate transport feedback must not use AntD static Modal.warning because it can fail to render in this app context')
assert.match(tabSource, /import \{ formatPurchaseDuplicateNotice \} from ['"]\.\/purchaseDuplicateNotice['"]/, 'ReplenishmentPlanTab must use the shared duplicate purchase notice helper')
assert.match(purchaseDuplicateNoticeSource, /function formatPurchaseDuplicateNotice\(drafts: PurchaseDraftRow\[\],\s*orders: PurchaseOrder\[\]\)[\s\S]*已加入采购单[\s\S]*可继续重复加入/, 'duplicate notice must explain where the product was already added while explicitly allowing repeated add')
assert.match(purchaseDuplicateNoticeSource, /formatPurchaseDuplicateNotice[\s\S]*formatPurchaseTransportSource\(source\)/, 'duplicate notice must include purchase order title, number, status, and quantity source text')
assert.match(purchaseDuplicateNoticeSource, /purchaseDraftNoticeLines\(drafts\)/, 'duplicate notice must inspect draft transports independently from positive submit quantities')
assert.doesNotMatch(purchaseDuplicateNoticeSource, /purchaseDraftNoticeLines[\s\S]*\.filter\(\(quantityDraft\) => quantityDraft\.quantity > 0\)/, 'duplicate notice must still show existing purchase facts when the current suggested quantity is zero')
assert.doesNotMatch(tabSource, /duplicatePurchaseTransportMessage|hasPositivePurchaseDraftQuantity/, 'blocking duplicate helper functions must be removed from the replenishment tab')
assert.match(purchaseDraftsSource, /air:\s*buildPurchaseDraftQuantity\(['"]AIR['"]/, 'single-row add must expose an AIR quantity in the product draft row')
assert.match(purchaseDraftsSource, /sea:\s*buildPurchaseDraftQuantity\(['"]SEA['"]/, 'single-row add must expose a SEA quantity in the product draft row')
assert.match(purchaseDraftsSource, /airSuggestedUnits/, 'AIR draft quantity must default from the air suggestion')
assert.match(purchaseDraftsSource, /airCalculatedUnits/, 'AIR draft must preserve the raw calculated air quantity for display')
assert.match(purchaseDraftsSource, /seaSuggestedUnits/, 'SEA draft quantity must default from the sea suggestion')
assert.match(purchaseDraftsSource, /seaCalculatedUnits/, 'SEA draft must preserve the calculated sea quantity for display')
assert.match(purchaseDraftsSource, /export function filterBatchPurchaseDrafts[\s\S]*draft\.air\.quantity > 0 \|\| draft\.sea\.quantity > 0/, 'batch purchase drafts must hide product rows whose air and sea suggestions are both zero')
assert.match(tabSource, /const calculableRows = targetRows\.filter\(\(item\) => !item\.calculationBlocked\)[\s\S]*const allDrafts = calculableRows\.flatMap\(\(item\) => buildPurchaseDrafts\(item,\s*query\.siteCode\)\)[\s\S]*const drafts = source === ['"]batch['"] \? filterBatchPurchaseDrafts\(allDrafts\) : allDrafts/, 'batch purchase modal must reject blocked rows and filter zero-suggestion products before rendering')
assert.doesNotMatch(tabSource, /dedupePurchaseDrafts\(drafts|dedupedDrafts|usedTransportKeys/, 'opening the purchase modal must not clear already-planned quantities because repeated add is allowed')
assert.match(tabSource, /const nextOrders = await loadEditablePurchaseOrders\(\)[\s\S]*setPurchaseDuplicateNotice\(formatPurchaseDuplicateNotice\(drafts,\s*purchasePlanningScopeOrders\(nextOrders\)\)\)[\s\S]*setPurchaseDrafts\(drafts\)[\s\S]*setPurchaseModalOpen\(true\)/, 'opening the purchase modal must warn about existing purchase lines while still rendering the original draft quantities')
assert.match(tabSource, /title:\s*['"]空运['"][\s\S]*renderDraftQuantityEditor\(draft,\s*['"]air['"]\)[\s\S]*title:\s*['"]海运['"][\s\S]*renderDraftQuantityEditor\(draft,\s*['"]sea['"]\)/, 'purchase modal must show air and sea quantities in the same product row')
assert.match(tabSource, /计算[\s\S]*quantityDraft\.calculatedQuantity[\s\S]*\/ 建议[\s\S]*<InputNumber/, 'purchase modal must show calculation text before the editable suggested quantity input')
assert.doesNotMatch(tabSource, /计算[\s\S]*quantityDraft\.calculatedQuantity[\s\S]*建议 \{formatQuantity\(quantityDraft\.suggestedQuantity\)\}/, 'purchase modal must not render suggested quantity as static text outside the input')
assert.match(cssSource, /replenishment-plan-draft-transport-cell \{[\s\S]*flex-direction:\s*row/, 'purchase modal calculation text and suggested input must sit on one line')
assert.doesNotMatch(tabSource, /flatMap\(\(item\) => buildPurchaseDrafts\(item, query\.siteCode\)\)\s*\.filter/, 'opening the purchase modal must not hide zero-quantity air or sea rows')
assert.match(tabSource, /validDrafts = purchaseDraftLines\(purchaseDrafts\)/, 'submitting must include all positive air and sea quantities in one purchase order request')
assert.match(tabSource, /addPurchaseOrderItems\(latestSelectedPurchaseOrder\.id,\s*\{\s*items\s*\}\)/, 'positive air and sea drafts must submit together to the latest verified selected purchase order')
assert.doesNotMatch(tabSource, /order\.storeCode\s*===\s*query\?\.storeCode/, 'purchase modal must not hide same logical-store purchase orders from another site storeCode')
assert.match(tabSource, /function editablePurchaseOrders[\s\S]*order\.status !== ['"]submitted['"][\s\S]*order\.status !== ['"]done['"][\s\S]*!isHistoricalPurchaseOrder\(order\)/, 'purchase order selector must only expose editable non-historical orders')
assert.match(tabSource, /function purchasePlanningScopeOrders[\s\S]*order\.status !== ['"]deleted['"][\s\S]*order\.status !== ['"]done['"][\s\S]*!isHistoricalPurchaseOrder\(order\)/, 'replenishment add/dedupe scope must ignore deleted, completed, and imported historical orders so deleting from the current purchase order allows adding again')
const planningScopeBlock = tabSource.match(/function purchasePlanningScopeOrders[\s\S]*?\n\}/)?.[0] || ''
assert.doesNotMatch(planningScopeBlock, /submitted/, 'current purchase-order duplicate scope must include submitted orders that are still part of the procurement flow')
assert.match(tabSource, /function isHistoricalPurchaseOrder\(order: PurchaseOrder\)[\s\S]*order\.orderNo[\s\S]*startsWith\(['"]PO-HIST-['"]\)/, 'replenishment add/dedupe scope must identify historical backfill purchase orders by PO-HIST order number')
assert.doesNotMatch(tabSource, /REPLENISHMENT_PLAN_PURCHASE_CACHE_KEY|localPurchaseTransportKeys|loadLocalPurchaseTransportKeys|markLocalPurchaseDraftLines|reconcileLocalPurchaseTransportKeys/, 'added purchase status must not rely on local cache; it must be derived from current purchase orders')
assert.match(purchaseProgressSource, /export function summarizePurchasePlanProgress/, 'replenishment plan must expose a pure current-plan purchase progress summary')
assert.match(purchaseProgressSource, /totalReplenishmentSkuCount[\s\S]*addedSkuCount[\s\S]*partialSkuCount[\s\S]*remainingSkuCount[\s\S]*airSkuCount[\s\S]*airQuantity[\s\S]*seaSkuCount[\s\S]*seaQuantity[\s\S]*orderLabels/, 'purchase progress summary must include complete, partial, and transport quantity coverage')
assert.match(purchaseProgressSource, /normalizeText\(allocation\.site\) !== normalizedSiteCode/, 'purchase progress summary must count current-site allocations without filtering by the order anchor store code')
assert.doesNotMatch(purchaseProgressSource, /order\.storeCode\s*===|anchorStoreCode/, 'purchase progress summary must not site-isolate same logical-store purchase orders by order storeCode')
assert.match(tabSource, /summarizePurchasePlanProgress\(searchMatchedRows,\s*purchasePlanningOrders,\s*query\?\.siteCode\)/, 'top current-plan summary must be derived from the current rows and current purchase-order facts')
assert.match(tabSource, /replenishment-plan-progress-summary[\s\S]*当前计划[\s\S]*已加入[\s\S]*还剩/, 'ReplenishmentPlanTab must show a top current-plan summary with joined orders and remaining products')
assert.match(tabSource, /const purchaseTransportQuantities = useMemo\(\s*\(\) => purchaseOrderTransportQuantities\(purchasePlanningOrders\),\s*\[purchasePlanningOrders\]\s*\)/, 'list coverage status must be derived from current purchase-order quantities')
assert.match(tabSource, /type PurchaseTransportSource = \{[\s\S]*orderTitle\?: string[\s\S]*orderNo\?: string[\s\S]*orderStatus\?: string[\s\S]*quantity\?: number/, 'added purchase status must keep the source purchase order title, number, status, and quantity for explanation')
assert.match(tabSource, /const purchaseTransportSources = useMemo\(\s*\(\) => purchaseOrderTransportSources\(purchasePlanningOrders\),\s*\[purchasePlanningOrders\]\s*\)/, 'list added status must derive an explanatory source map from current purchase-order facts')
assert.match(tabSource, /function purchaseOrderTransportSources\(orders: PurchaseOrder\[\]\)[\s\S]*pskuSiteTransportKey\(item\.partnerSku,\s*allocation\.site,\s*allocation\.transportMode\)[\s\S]*orderTitle:\s*order\.title[\s\S]*orderNo:\s*order\.orderNo[\s\S]*orderStatus:\s*order\.status/, 'purchase order source map must preserve the exact current order that made a transport mode already added')
assert.match(tabSource, /const tooltipLines = \[[\s\S]*formatPurchaseTransportSource\(source\)[\s\S]*<Tooltip title=\{tooltipLines\.join\(['"]\\n['"]\)\}[\s\S]*\{tag\}/, 'added suggestion tags must show the source purchase order in a tooltip')
assert.match(tabSource, /renderSuggestionTransportTag\(item,\s*['"]AIR['"]\)[\s\S]*renderSuggestionTransportTag\(item,\s*['"]SEA['"]\)/, 'suggestion column must show add status for both air and sea transports')
assert.match(tabSource, /dataIndex:\s*['"]seaSuggestedUnits['"][\s\S]*width:\s*['"]17%['"]/, 'suggestion column must be wider enough for calculation, suggestion, and add-status labels')
assert.match(tabSource, /已加[\s\S]*部分[\s\S]*待加|待加[\s\S]*无需/, 'suggestion status labels must distinguish complete, partial, pending, and no-suggestion transports')
assert.match(tabSource, /const tagColor = seaEtaRisk \? ['"]red['"][\s\S]*status === ['"]部分['"] \? ['"]orange['"][\s\S]*<Tag color=\{tagColor\}/, 'suggestion tags must preserve red sea-risk priority and mark partial purchase coverage')
assert.match(cssSource, /replenishment-plan-suggestion-status\.is-added \{[\s\S]*background:\s*#f3f4f6;[\s\S]*color:\s*#4b5563;/, 'added suggestion status badge must be gray, not a green success state')
assert.doesNotMatch(tabSource, /purchaseOrderTransportKeys\(purchasePlanningScopeOrders\(nextOrders\)\)[\s\S]*dedupePurchaseDrafts/, 'opening purchase modal must not remove already-planned PSKU/site/transport quantities from current purchase orders')
assert.match(tabSource, /const latestOrders = await loadEditablePurchaseOrders\(\)[\s\S]*const latestEditableOrders = editablePurchaseOrders\(latestOrders\)[\s\S]*const latestSelectedPurchaseOrder = latestEditableOrders\.find[\s\S]*addPurchaseOrderItems\(latestSelectedPurchaseOrder\.id,\s*\{\s*items\s*\}\)/, 'submitting replenishment purchase drafts must re-check that the target order is still editable, then add items without duplicate blocking')
assert.doesNotMatch(tabSource, /duplicatePskuSiteTransportMessage\(validDrafts,\s*latestPurchasePlanningOrders\)|const latestPurchasePlanningOrders = purchasePlanningScopeOrders\(latestOrders\)/, 'submitting replenishment purchase drafts must not block repeated add by existing current purchase-order lines')
assert.doesNotMatch(tabSource, /duplicatePskuSiteMessage\(validDrafts,\s*selectedPurchaseOrder\)/, 'submitting must not rely on the stale selected purchase-order snapshot for duplicate checks')
assert.match(tabSource, /function purchaseOrderTransportQuantities[\s\S]*pskuSiteTransportKey\(item\.partnerSku,\s*allocation\.site,\s*allocation\.transportMode\)[\s\S]*numericQuantity\(allocation\.quantity\)/, 'purchase coverage must aggregate quantities by PSKU, site, and transport mode')
assert.doesNotMatch(purchaseDraftsSource, /dedupePurchaseDrafts|hasUnplannedDraftTransport/, 'purchase draft helpers must not retain old duplicate-clearing logic because repeated add is allowed')
assert.doesNotMatch(tabSource, /title:\s*['"]已加入['"]|title:\s*['"]剩余['"]/, 'ReplenishmentPlanTab must not display already-added or remaining-copy as purchase modal table columns')
assert.doesNotMatch(tabSource, /title:\s*['"]加入采购数量['"]/, 'ReplenishmentPlanTab must not show purchase quantity as a list column')
assert.doesNotMatch(tabSource, /title:\s*['"]操作['"]/, 'ReplenishmentPlanTab must not spend a separate table column on row actions')
