import { expect, test } from '@playwright/test'
import { noonImageWithoutExtension } from './in-transit-goods.fixtures'
import {
  setupEmptyInTransitRoutes,
  setupMaintainsInTransitRoutes
} from './in-transit-goods.routes'

function expectedInTransitDurationText(domesticReceivedAt: string) {
  const received = new Date(domesticReceivedAt)
  const now = new Date()
  const receivedDay = new Date(received.getFullYear(), received.getMonth(), received.getDate())
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
  const days = Math.max(Math.floor((today.getTime() - receivedDay.getTime()) / 86_400_000), 0)
  return `在途时间 ${days} 天`
}

test('renders real empty in-transit batch state without mock rows', async ({ page }) => {
  const routeState = await setupEmptyInTransitRoutes(page)
  await page.goto('/purchase/in-transit-goods?devSession=1&devRole=boss&grantInTransitGoods=1')

  const pageRoot = page.getByTestId('in-transit-goods-page')
  await expect(pageRoot).toBeVisible()
  await expect(pageRoot.getByText('暂无在途批次')).toBeVisible()
  await expect(pageRoot).not.toContainText('历史货代A')
  await expect(pageRoot).not.toContainText('BATCH-001')
  await expect(pageRoot).not.toContainText('义特')
  await expect.poll(() => routeState.batchListRequestedUrl).toContain('/api/in-transit-goods/batches')
  expect(routeState.batchListRequestedUrl).toContain('statusScope=all')
  expect(routeState.batchListRequestedUrl).toContain('page=1')
  expect(routeState.batchListRequestedUrl).toContain('pageSize=20')
  expect(routeState.batchListRequestedUrl).toContain('sortField=createdAt')
  expect(routeState.batchListRequestedUrl).toContain('sortDirection=desc')
})

test('maintains in-transit batch basics without expanded fields', async ({ page }) => {
  const routeState = await setupMaintainsInTransitRoutes(page)
  await page.goto('/purchase/in-transit-goods?devSession=1&devRole=boss&grantInTransitGoods=1')

  const pageRoot = page.getByTestId('in-transit-goods-page')
  await expect(pageRoot).toBeVisible()
  await expect(pageRoot).not.toContainText('维护在途批次、货代归一、运输方式、目标仓和 ETA。')
  const toolbar = pageRoot.locator('.in-transit-page__toolbar')
  await expect(pageRoot.locator('.in-transit-page__actions')).toHaveCount(0)
  await expect(toolbar.getByPlaceholder('PSKU/商品')).toBeVisible()
  await expect(toolbar.getByRole('button', { name: '刷新' })).toBeVisible()
  await expect(toolbar.getByRole('button', { name: '导入预览' })).toBeVisible()
  await expect(toolbar.getByRole('button', { name: '新建批次' })).toBeVisible()
  await expect(pageRoot.getByText('启客').first()).toBeVisible()
  await expect(pageRoot.getByText('海运').first()).toBeVisible()
  await expect(pageRoot.getByText('空运')).toBeVisible()
  await expect(pageRoot).not.toContainText('已归一')
  await expect(pageRoot.getByRole('columnheader', { name: '目的地' })).toHaveCount(0)
  await expect(pageRoot.getByText('目的仓', { exact: true })).toBeVisible()
  await expect(pageRoot.getByRole('columnheader', { name: '时间节点' })).toBeVisible()
  await expect(pageRoot.getByRole('columnheader', { name: '时间统计' })).toBeVisible()
  await expect(pageRoot.getByText('官方预计到仓 2026-06-03')).toBeVisible()
  await expect(pageRoot.getByRole('row', { name: /BATCH-002/ })).toContainText(
    expectedInTransitDurationText('2026-06-10T08:00:00')
  )
  await expect(pageRoot.getByRole('columnheader', { name: '批次号' })).toBeVisible()
  await expect(pageRoot.getByRole('row', { name: /BATCH-002/ })).toContainText('目的地 RUH 利雅得')
  const batchHeaders = await pageRoot.locator('.ant-table-thead th').evaluateAll((nodes) =>
    nodes.map((node) => node.textContent?.trim() || '')
  )
  expect(batchHeaders.indexOf('货代')).toBeLessThan(batchHeaders.indexOf('批次号'))
  const batchTableRows = pageRoot.locator('.in-transit-page__table .ant-table-tbody tr.ant-table-row')
  await expect(batchTableRows.first()).toHaveClass(/in-transit-row--odd/)
  await expect(batchTableRows.nth(1)).toHaveClass(/in-transit-row--even/)
  await expect(pageRoot.getByRole('columnheader', { name: '批次', exact: true })).toHaveCount(0)
  await expect(pageRoot.getByRole('button', { name: '箱数 2' })).toBeVisible()
  await expect(pageRoot.getByText('PSKU 3')).toBeVisible()
  await expect(pageRoot).not.toContainText('目标店铺')
  await expect(pageRoot).not.toContainText('目标仓')
  await expect(pageRoot).not.toContainText('ETA')
  await expect(pageRoot).not.toContainText('备注')
  await expect(pageRoot.getByText('发货 160')).toBeVisible()
  await expect(pageRoot.getByText('入仓 40')).toBeVisible()
  await expect(pageRoot.getByText('重量 -').first()).toBeVisible()
  await expect(pageRoot.getByText('体积 -').first()).toBeVisible()
  await expect(pageRoot.getByText('清关中')).toBeVisible()
  await expect(pageRoot.getByText('2026-06-01', { exact: true })).toBeVisible()
  await expect(pageRoot.getByText('2026-06-01 10:30:00')).toHaveCount(0)
  await expect(pageRoot.getByText('清关资料已提交')).toBeVisible()
  await expect(pageRoot).not.toContainText('采购单')
  await expect(pageRoot).not.toContainText('费用')
  expect(routeState.lastBatchListUrl).toContain('statusScope=all')
  expect(routeState.lastBatchListUrl).toContain('page=1')
  expect(routeState.lastBatchListUrl).toContain('pageSize=20')
  expect(routeState.lastBatchListUrl).toContain('sortField=createdAt')
  expect(routeState.lastBatchListUrl).toContain('sortDirection=desc')
  await pageRoot.locator('.ant-table-thead th').filter({ hasText: '时间节点' }).click()
  await expect.poll(() => routeState.lastBatchListUrl).toContain('sortField=etaDate')
  expect(routeState.lastBatchListUrl).toContain('sortDirection=asc')

  await page.getByRole('row', { name: /BATCH-UNMATCHED/ }).getByRole('button', { name: '匹配货代' }).click()
  const aliasDrawer = page.locator('.ant-drawer').filter({ hasText: '货代归一' })
  await expect(aliasDrawer).toBeVisible()
  await expect(aliasDrawer.locator('input[readonly]').first()).toHaveValue('历史货代A')
  await aliasDrawer.locator('.ant-select').click()
  await page.getByTitle('启客').click()
  await aliasDrawer.getByRole('button', { name: '保存归一' }).click()
  await expect.poll(() => routeState.savedAliasBody).not.toBeNull()
  expect(routeState.savedAliasBody).toMatchObject({ rawForwarderName: '历史货代A', standardForwarderId: 51002 })

  const forwarderFilter = page.locator('.in-transit-page__toolbar .ant-select').filter({
    has: page.locator('input[aria-label="货代"]')
  })
  await forwarderFilter.click()
  await expect(page.getByTitle('启客')).toBeVisible()
  await expect(page.getByTitle('易通')).toBeVisible()
  await expect(page.getByTitle('义特')).toBeVisible()
  await expect(page.getByTitle('历史货代A')).toHaveCount(0)
  await page.getByTitle('启客').click()
  await expect.poll(() => routeState.lastBatchListUrl).toContain('standardForwarderId=51002')
  await forwarderFilter.click()
  await page.getByTitle('义特').click()
  await expect.poll(() => routeState.lastBatchListUrl).toContain('standardForwarderId=51001')
  const destinationFilter = page.locator('.in-transit-page__toolbar .ant-select').filter({
    has: page.locator('input[aria-label="目的地"]')
  })
  await destinationFilter.click()
  await expect(page.getByTitle('DB 迪拜')).toBeVisible()
  await expect(page.getByTitle('RUH 利雅得')).toBeVisible()
  await page.getByTitle('RUH 利雅得').click()
  await expect.poll(() => routeState.lastBatchListUrl).toContain('targetStoreCode=RUH')

  await expect(pageRoot.getByRole('button', { name: /查看箱子/ })).toHaveCount(0)
  await page.getByRole('row', { name: /BATCH-002/ }).getByRole('button', { name: 'PSKU 3' }).click()
  const workspaceTabs = page.getByTestId('workspace-tabs-bar')
  await expect(workspaceTabs.getByRole('tab', { name: /商品明细/ })).toHaveAttribute('aria-selected', 'true')
  await expect(pageRoot.getByRole('tab', { name: '产品维度' })).toHaveAttribute('aria-selected', 'true')
  await expect(pageRoot.getByRole('columnheader', { name: '产品' })).toBeVisible()
  await expect(pageRoot.getByRole('columnheader', { name: '所在箱子' })).toBeVisible()
  await workspaceTabs.getByRole('tab', { name: '在途商品' }).click()
  await expect(pageRoot.getByRole('columnheader', { name: '批次号' })).toBeVisible()

  await page.getByRole('row', { name: /BATCH-002/ }).getByRole('button', { name: '箱数 2' }).click()
  await expect(page.getByRole('dialog', { name: /查看箱子/ })).toHaveCount(0)
  await expect(workspaceTabs.getByRole('tab', { name: /商品明细/ })).toHaveAttribute('aria-selected', 'true')
  await expect(pageRoot).not.toContainText('箱子详情 - BATCH-002')
  await expect(pageRoot.locator('.in-transit-detail__header')).toHaveCSS('justify-content', 'flex-start')
  await expect(pageRoot.getByRole('tab', { name: '箱子维度' })).toHaveAttribute('aria-selected', 'true')
  await expect(pageRoot.getByRole('columnheader', { name: '箱号' })).toBeVisible()
  await expect(pageRoot.getByRole('columnheader', { name: '箱内产品' })).toBeVisible()
  await expect(pageRoot.getByRole('row', { name: /XGGEUAE04029-1/ })).toHaveCount(1)
  const activeBoxDetailPane = pageRoot.locator('.in-transit-detail .ant-tabs-tabpane-active')
  await expect(activeBoxDetailPane.locator('.ant-table-tbody tr.ant-table-row').first()).toHaveClass(/in-transit-row--odd/)
  await expect(activeBoxDetailPane.getByAltText('折叠手机壳')).toHaveAttribute('src', `${noonImageWithoutExtension}.jpg`)
  await expect(activeBoxDetailPane.getByText('折叠手机壳').first()).toBeVisible()
  await expect(activeBoxDetailPane).not.toContainText('Noon Folding Phone Case')
  await expect(activeBoxDetailPane.getByText('PSKU PSKU-AE-001')).toBeVisible()
  await expect(activeBoxDetailPane.getByText('PSKU PSKU-AE-009')).toBeVisible()
  const boxProductsCell = activeBoxDetailPane.locator('.in-transit-box-products')
  await expect(boxProductsCell).not.toContainText('发货')
  await expect(boxProductsCell).not.toContainText('入仓')
  await expect(pageRoot.getByRole('columnheader', { name: '箱规' })).toBeVisible()
  await expect(pageRoot.getByRole('row', { name: /XGGEUAE04029-1/ })).toContainText('PSKU 2')
  await expect(pageRoot.getByRole('row', { name: /XGGEUAE04029-1/ })).toContainText('发货 160')
  await expect(pageRoot).not.toContainText('PARENT-AE-001')
  await expect(pageRoot.getByText('SKU-AE-001', { exact: true })).toHaveCount(0)
  await expect(activeBoxDetailPane.getByText('无图')).toBeVisible()

  await pageRoot.getByRole('tab', { name: '产品维度' }).click()
  const activeDetailPane = pageRoot.locator('.in-transit-detail .ant-tabs-tabpane-active')
  const productTableRows = activeDetailPane.locator('.ant-table-tbody tr.ant-table-row')
  await expect(productTableRows.first()).toHaveClass(/in-transit-row--odd/)
  await expect(productTableRows.nth(1)).toHaveClass(/in-transit-row--even/)
  await expect(activeDetailPane.locator('.in-transit-product-boxes__item').filter({ hasText: 'XGGEUAE04029-1' })).toHaveCount(2)
  await expect(activeDetailPane.getByText('折叠手机壳').first()).toBeVisible()
  await expect(activeDetailPane).not.toContainText('Noon Folding Phone Case')
  await expect(activeDetailPane.locator('.in-transit-product-boxes__item').first()).toContainText('数量 100')
  await activeDetailPane.getByRole('row', { name: /PSKU-AE-001/ }).getByRole('button', { name: '运费历史' }).click()
  const skuFreightDrawer = page.locator('.ant-drawer').filter({ hasText: 'SKU运费历史' })
  await expect(skuFreightDrawer).toBeVisible()
  await expect.poll(() => routeState.skuHistoryUrl).toContain('psku=PSKU-AE-001')
  expect(routeState.forwarderComparisonUrl).toContain('transportMode=AIR')
  expect(routeState.forwarderComparisonUrl).toContain('destinationCode=RUH')
  await expect(skuFreightDrawer.getByText('义特').first()).toBeVisible()
  await expect(skuFreightDrawer.getByText('¥432.00').first()).toBeVisible()
  await skuFreightDrawer.getByRole('button', { name: /关\s*闭/ }).click()
  await workspaceTabs.getByRole('tab', { name: '在途商品' }).click()
  await expect(pageRoot.getByRole('columnheader', { name: '批次号' })).toBeVisible()

  await toolbar.scrollIntoViewIfNeeded()
  await toolbar.getByRole('button', { name: '导入预览' }).click()
  const importDrawer = page.locator('.ant-drawer').filter({ hasText: '历史数据导入预览' })
  await expect(importDrawer).toBeVisible()
  const downloadPromise = page.waitForResponse('**/api/in-transit-goods/import-template')
  await importDrawer.getByRole('button', { name: '下载模板' }).click()
  await downloadPromise
  await page.setInputFiles('input[type=file]', {
    name: '错误在途.csv',
    mimeType: 'text/csv',
    buffer: Buffer.from('批次号,运输方式,PSKU,SKU\nBATCH-ERR,铁路,PSKU-ERR,SKU-ERR\n')
  })
  await expect(importDrawer.getByText('错误 1')).toBeVisible()
  await expect(importDrawer.getByText('运输方式只支持海运或空运。').first()).toBeVisible()
  await expect(importDrawer.getByRole('button', { name: '确认导入' })).toBeDisabled()
  await page.setInputFiles('input[type=file]', {
    name: '历史在途.csv',
    mimeType: 'text/csv',
    buffer: Buffer.from('批次号,运输方式,PSKU,SKU,发货数量\nBATCH-IMP,SEA,PSKU-IMP-001,SKU-IMP-001,10\n')
  })
  await expect(importDrawer.getByText('预览校验通过')).toBeVisible()
  await expect(importDrawer.getByText('BATCH-IMP')).toBeVisible()
  await expect(importDrawer.getByRole('columnheader', { name: '目的地' })).toBeVisible()
  await expect(importDrawer).not.toContainText('ETA')
  await expect(importDrawer.getByText('XGGEUAE04029-1')).toBeVisible()
  await importDrawer.getByRole('button', { name: '确认导入' }).click()
  await expect.poll(() => routeState.confirmImportUrl).toContain('/api/in-transit-goods/imports/56011/confirm')
  await expect(importDrawer).toBeHidden()

  await toolbar.scrollIntoViewIfNeeded()
  await toolbar.getByPlaceholder('PSKU/商品').fill('PSKU-AE-001')
  await expect.poll(() => routeState.lastBatchListUrl).toContain('skuKeyword=PSKU-AE-001')
  await toolbar.getByRole('button', { name: '新建批次' }).click()
  await page.locator('.ant-drawer').locator('#standardForwarderId').click()
  await page.getByTitle('启客').click()
  await page.getByPlaceholder('历史记录里的货代名称').fill('启客')
  await page.locator('.ant-drawer').locator('#transportMode').click()
  await page.getByTitle('海运').click()
  await page.locator('.ant-drawer').locator('#targetStoreCode').click()
  await page.getByTitle('DB 迪拜').click()
  await page.getByPlaceholder('如 FBN-DXB').fill('FBN-DXB')
  await page.getByPlaceholder('YYYY-MM-DD').first().fill('2026-05-28')
  await page.getByPlaceholder('YYYY-MM-DD').nth(1).fill('2026-06-18')
  await page.getByRole('button', { name: /保\s*存/ }).click()
  await expect.poll(() => routeState.savedBody).not.toBeNull()
  expect(routeState.savedBody).toMatchObject({
    standardForwarderId: 51002,
    rawForwarderName: '启客',
    transportMode: 'SEA',
    targetStoreCode: 'DB',
    targetWarehouseName: 'FBN-DXB'
  })
  expect(routeState.savedBody).not.toHaveProperty('purchaseOrderNo')
  expect(routeState.savedBody).not.toHaveProperty('feeStatus')
  expect(routeState.savedBody).not.toHaveProperty('remark')

  await page.getByRole('button', { name: /保\s*存/ }).waitFor({ state: 'detached' })
  await page.getByRole('row', { name: /BATCH-002/ }).getByRole('button', { name: /编辑/ }).click()
  const drawer = page.locator('.ant-drawer').filter({ hasText: '编辑在途批次' })
  await expect(drawer.getByText('商品明细')).toBeVisible()
  await expect(drawer.getByText('备注')).toHaveCount(0)
  await expect(drawer.getByText('PSKU-AE-001', { exact: true }).first()).toBeVisible()
  await expect.poll(() => routeState.batchFreightCostUrl).toContain('/api/in-transit-goods/batches/53002/freight-costs')
  await expect(drawer.getByText('实际运费')).toBeVisible()
  await expect(drawer.getByText('AR25012055917')).toBeVisible()
  await expect(drawer.getByText('物流时间线')).toBeVisible()
  await expect(drawer.getByText('清关资料已提交')).toBeVisible()
  await expect(drawer.getByRole('button', { name: /^保存$/ })).toHaveCount(0)
  await expect(drawer.getByRole('button', { name: '添加节点' })).toHaveCount(0)
  await drawer.getByRole('button', { name: '添加商品' }).click()
  await page.getByPlaceholder('箱号', { exact: true }).fill('XGGEUAE04029-2')
  await page.getByPlaceholder('商品 PSKU').fill('PSKU-AE-002')
  await page.getByPlaceholder('商品名称').fill('数据线')
  await page.getByPlaceholder('发货数量').fill('12')
  await page.getByPlaceholder('已入仓数量').fill('5')
  await page.getByPlaceholder('箱数', { exact: true }).fill('2')
  await page.getByPlaceholder('单箱重量').fill('1.500000')
  await page.getByPlaceholder('单箱体积').fill('0.020000')
  await page.getByPlaceholder('外部箱号').fill('ET-BOX-001')
  await page.getByPlaceholder('包裹追踪号').fill('TRK-PKG-001')
  await page.getByPlaceholder('包裹重量').fill('12.500000')
  await page.getByPlaceholder('包裹长').fill('60')
  await page.getByPlaceholder('包裹宽').fill('40')
  await page.getByPlaceholder('包裹高').fill('30')
  await page.getByPlaceholder('包裹体积').fill('0.072000')
  await page.getByPlaceholder('仓库称重').fill('12.800000')
  await page.getByPlaceholder('仓库测量长').fill('61')
  await page.getByPlaceholder('仓库测量宽').fill('41')
  await page.getByPlaceholder('仓库测量高').fill('31')
  await page.getByPlaceholder('仓库测量体积').fill('0.077531')
  await page.getByPlaceholder('包裹状态').fill('已出库')
  await page.getByPlaceholder('物流状态').fill('customs_clearance')
  await drawer.getByRole('button', { name: '保存商品' }).click()
  await expect.poll(() => routeState.savedLineBody).not.toBeNull()
  expect(routeState.savedLineBody).toMatchObject({
    boxNo: 'XGGEUAE04029-2',
    psku: 'PSKU-AE-002',
    shippedQuantity: 12,
    receivedQuantity: 5,
    cartonCount: 2,
    packageTrackingNo: 'TRK-PKG-001',
    logisticsStatus: 'customs_clearance'
  })
  expect(routeState.savedLineBody).not.toHaveProperty('remainingQuantity')
  expect(routeState.savedLineBody).not.toHaveProperty('purchaseOrderNo')
  await expect(drawer.getByRole('button', { name: /删除/ }).first()).toBeEnabled()
  await drawer.getByRole('button', { name: /删除/ }).first().click()
  await expect.poll(() => routeState.deletedLineUrl).toContain('/api/in-transit-goods/batches/53002/lines/54001')
})
