import type { ProcurementRequirementRecord } from './types'
import { buildMockImage } from './mockCandidateFactory'
import {
  createEditingCandidates,
  createRunningCandidates,
  createSummaryReadyCandidates
} from './mockCandidateScenarios'

export function createMockDemandBatches(): ProcurementRequirementRecord[] {
  return [
    {
      id: 'dem-01',
      poolId: 'pool-01',
      hasPool: true,
      demandNo: 'PC-20260428-01',
      orderNo: 'PO-20260428-0916',
      poolVersion: 1,
      demandTitle: '阿拉伯风便携电香炉礼盒采购',
      searchKeyword: '电香炉 礼盒 阿拉伯 便携',
      sourcePlatform: 'Noon',
      sourceUrl: 'https://www.noon.com/uae-en/sample-burner-gift-set',
      sourceTitle: '阿拉伯风便携电香炉礼盒采购',
      sourceImageUrl: buildMockImage('Noon 主图', '#1d4ed8', '#0f766e'),
      sourceCollectionStatus: 'SUCCESS',
      sourceCollectedAt: '2026-04-28 09:20',
      sourceCollectionMessage: '源头商品标题、图片和详情已采集。',
      referenceImageUrl: buildMockImage('参考图', '#2563eb', '#1d4ed8'),
      packageImageUrl: buildMockImage('包装图', '#0f766e', '#164e63'),
      candidateCollectionStatus: 'SUCCESS',
      candidateCount: 10,
      recommendedCandidateCount: 5,
      candidateCollectionMethod: '1688 图搜 / 候选采集',
      candidateCollectedAt: '2026-04-28 09:38',
      candidateCollectionMessage: '已读取 1688 候选采集结果。',
      targetPriceMin: 18.5,
      targetPriceMax: 24,
      targetQuantity: 120,
      expectedDelivery: '首批 7 天内发往义乌集货仓',
      targetSite: 'AE / SA',
      specialRequirement: '礼盒感必须到位，外观接近 Noon 爆款，优先低 MOQ 可试单工厂。',
      targetMaterial: '金属外壳 / 陶瓷发热仓',
      targetPowerMode: 'USB 充电 / 可充电',
      targetSizeText: '便携桌面款，约 10 x 10 x 14 cm',
      targetPackageType: '彩盒 / 礼盒包装',
      ownerName: '张敏 / 运营',
      status: 'POOL_INQUIRY_RUNNING',
      top10Count: 10,
      createdAt: '2026-04-28 09:16',
      updatedAt: '2026-04-28 16:18',
      pendingConfirmations: [],
      resultNotice: '系统已自动把前 5 条加入待选池并发起询价；待选池最多 5 个，补入备选前请先移出一个待选候选。',
      candidates: createEditingCandidates()
    },
    {
      id: 'dem-02',
      poolId: 'pool-02',
      hasPool: true,
      demandNo: 'PC-20260428-02',
      orderNo: 'PO-20260428-1028',
      poolVersion: 2,
      demandTitle: '礼盒香炉补询价需求',
      searchKeyword: '便携 香炉 礼盒 义乌 工厂',
      sourcePlatform: 'Noon',
      sourceUrl: 'https://www.noon.com/uae-en/sample-burner-gift-set-v2',
      sourceTitle: '礼盒香炉补询价需求',
      sourceImageUrl: buildMockImage('Noon 次图', '#b45309', '#92400e'),
      sourceCollectionStatus: 'SUCCESS',
      sourceCollectedAt: '2026-04-28 10:35',
      sourceCollectionMessage: '源头商品标题、图片和详情已采集。',
      referenceImageUrl: buildMockImage('参考图 2', '#f59e0b', '#b45309'),
      packageImageUrl: buildMockImage('包装图 2', '#7c2d12', '#431407'),
      candidateCollectionStatus: 'SUCCESS',
      candidateCount: 10,
      recommendedCandidateCount: 5,
      candidateCollectionMethod: '1688 图搜 / 候选采集',
      candidateCollectedAt: '2026-04-28 10:58',
      candidateCollectionMessage: '已读取 1688 候选采集结果。',
      targetPriceMin: 19,
      targetPriceMax: 23.5,
      targetQuantity: 150,
      expectedDelivery: '先拿报价，确认工期后再走样品',
      targetSite: 'AE',
      specialRequirement: '重点看供应商回复效率和礼盒贴牌能力。',
      targetMaterial: '金属外壳 / 陶瓷发热仓',
      targetPowerMode: 'USB 充电 / 可充电',
      targetSizeText: '便携桌面款',
      targetPackageType: '礼盒包装',
      ownerName: '张敏 / 运营',
      status: 'POOL_INQUIRY_RUNNING',
      top10Count: 10,
      poolStartedAt: '2026-04-28 16:20',
      poolStartedBy: '王晶',
      createdAt: '2026-04-28 10:28',
      updatedAt: '2026-04-28 16:40',
      pendingConfirmations: [],
      resultNotice: '待选池自动询价正在执行，请关注回复、催发和异常状态。',
      candidates: createRunningCandidates()
    },
    {
      id: 'dem-03',
      poolId: 'pool-03',
      hasPool: true,
      demandNo: 'PC-20260427-03',
      orderNo: 'PO-20260427-1542',
      poolVersion: 3,
      demandTitle: '礼盒香炉询价结果总结',
      searchKeyword: '电热 香炉 礼盒 现货',
      sourcePlatform: 'Noon',
      sourceUrl: 'https://www.noon.com/uae-en/sample-burner-gift-set-summary',
      sourceTitle: '礼盒香炉询价结果总结',
      sourceImageUrl: buildMockImage('Noon 历史图', '#0f766e', '#0f172a'),
      sourceCollectionStatus: 'SUCCESS',
      sourceCollectedAt: '2026-04-27 15:50',
      sourceCollectionMessage: '源头商品标题、图片和详情已采集。',
      referenceImageUrl: buildMockImage('历史参考', '#134e4a', '#14532d'),
      packageImageUrl: buildMockImage('历史包装', '#166534', '#14532d'),
      candidateCollectionStatus: 'SUCCESS',
      candidateCount: 10,
      recommendedCandidateCount: 5,
      candidateCollectionMethod: '1688 图搜 / 候选采集',
      candidateCollectedAt: '2026-04-27 16:12',
      candidateCollectionMessage: '已读取 1688 候选采集结果。',
      targetPriceMin: 19.5,
      targetPriceMax: 22.5,
      targetQuantity: 200,
      expectedDelivery: '按 4 月 30 日前确认首单供应商为目标',
      targetSite: 'AE / SA / KW',
      specialRequirement: '优先稳定供货和礼盒贴牌能力，再考虑小幅差价。',
      targetMaterial: '金属外壳 / 陶瓷发热仓',
      targetPowerMode: 'USB 充电 / 可充电',
      targetSizeText: '便携桌面款',
      targetPackageType: '礼盒包装',
      ownerName: '张敏 / 运营',
      status: 'SUMMARY_READY',
      top10Count: 10,
      poolStartedAt: '2026-04-27 14:30',
      poolStartedBy: '王晶',
      createdAt: '2026-04-27 15:42',
      updatedAt: '2026-04-28 09:12',
      pendingConfirmations: [],
      resultNotice: '待选池自动询价已收口，可查看最终候选和 AI 总结。',
      finalDecisionNote: '当前按最终 2 个正式候选推进，候选 1 优先跟进，候选 2 作为补充。',
      aiSummary:
        'AI 总结：待选池首位供应商报价最低且礼盒支持贴牌，适合作为首选；第二候选回复速度快、MOQ 友好，可作为备选。其余候选要么 24 小时无回复，要么报价信息不足，不建议进入首单。',
      candidates: createSummaryReadyCandidates()
    }
  ]
}
