import type {
  ProductLastPublishTaskPayload,
  ProductListingPublishTaskPayload,
  ProductOperationStageCode,
  ProductSyncStatus
} from './productListTypes';

export type ProductListSummaryPayload = {
  ready: boolean;
  source?: string;
  message?: string;
  warnings: string[];
  storeCode?: string;
  skuParent?: string;
  currentZCode?: string;
  productMasterId?: number;
  productVariantId?: number;
  productSiteOfferId?: number;
  productSourceType?: string;
  partnerSku?: string;
  pskuCode?: string;
  offerCode?: string;
  title?: string;
  titleCn?: string;
  brand?: string;
  imageUrl?: string;
  galleryImages?: string[];
  barcode?: string;
  referencePrice?: string;
  originalPrice?: string;
  salePrice?: string;
  productFulltype?: string;
  skuGroup?: string | null;
  groupRef?: string | null;
  groupRefCanonical?: string | null;
  isActive?: boolean;
  maintenanceEnabled?: boolean;
  liveStatus?: string;
  statusCode?: string;
  listingStartedAt?: string;
  listingStartedSource?: string;
  operationStageCode?: ProductOperationStageCode | string;
  operationStageUpdatedAt?: string;
  operationStageUpdatedBy?: number;
  syncStatus?: ProductSyncStatus;
  lastSyncedAt?: string;
  lastDraftSavedAt?: string;
  detailBaselineStatus?: 'ready' | 'missing' | 'preparing' | 'failed' | string;
  detailBaselineMessage?: string;
  detailBaselineSyncedAt?: string;
  productVariantSpecStatus?: 'ready' | 'incomplete' | 'not_found' | string;
  productVariantSpecTotalCount?: number;
  productVariantSpecReadyCount?: number;
  productVariantSpecMaintainedCount?: number;
  variantCount?: number;
  siteOfferCount?: number;
  siteLabels: string[];
  liveStatuses: string[];
  historyMetaReady?: boolean;
  pendingKeyContentHistoryCount?: number;
  visibleKeyContentHistoryCount?: number;
  pendingKeyContentHistoryVisibleAfter?: string;
  totalFbnStock?: number;
  totalSupermallStock?: number;
  totalFbpStock?: number;
  viewsCount?: number;
  unitsSold?: number;
  salesAmount?: string;
  salesCurrency?: string;
  lastPublishTask?: ProductLastPublishTaskPayload;
  listingPublishTask?: ProductListingPublishTaskPayload;
};

export type ProductSummarySurface = {
  skuParent: string;
  currentZCode?: string;
  productMasterId?: number;
  productVariantId?: number;
  productSiteOfferId?: number;
  productSourceType?: string;
  partnerSku?: string;
  pskuCode?: string;
  offerCode?: string;
  storeCode?: string;
  title?: string;
  titleCn?: string;
  titleAr?: string;
  brand?: string;
  imageUrl?: string;
  galleryImages: string[];
  barcode?: string;
  currency?: string;
  referencePrice?: string;
  originalPrice?: string;
  salePrice?: string;
  productFulltype?: string;
  skuGroup?: string;
  groupRef?: string;
  groupRefCanonical?: string;
  liveStatus?: string;
  statusCode?: string;
  isActive?: boolean;
  maintenanceEnabled?: boolean;
  listingStartedAt?: string;
  listingStartedSource?: string;
  operationStageCode?: ProductOperationStageCode | string;
  operationStageUpdatedAt?: string;
  operationStageUpdatedBy?: number;
  syncStatus?: ProductSyncStatus;
  lastSyncedAt?: string;
  lastDraftSavedAt?: string;
  detailBaselineStatus?: 'ready' | 'missing' | 'preparing' | 'failed' | string;
  detailBaselineMessage?: string;
  detailBaselineSyncedAt?: string;
  productVariantSpecStatus?: 'ready' | 'incomplete' | 'not_found' | string;
  productVariantSpecTotalCount?: number;
  productVariantSpecReadyCount?: number;
  productVariantSpecMaintainedCount?: number;
  variantCount?: number;
  siteOfferCount?: number;
  siteLabels: string[];
  liveStatuses: string[];
  totalFbnStock?: number;
  totalSupermallStock?: number;
  totalFbpStock?: number;
  viewsCount?: number;
  unitsSold?: number;
  salesAmount?: string;
  salesCurrency?: string;
};
