import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const pageSource = readFileSync(join(process.cwd(), 'src/features/product-keywords/ProductKeywordDataPage.tsx'), 'utf8')

assert.match(pageSource, /data-testid="product-keyword-data-page"/)
assert.match(pageSource, /data-testid="product-keyword-store-filter"/)
assert.match(pageSource, /data-testid="product-keyword-status-filter"/)
assert.match(pageSource, /data-testid="product-keyword-table"/)
assert.match(pageSource, /OBSERVED/)
assert.match(pageSource, /ACTIVE/)
assert.match(pageSource, /已启用/)
assert.match(pageSource, /候选词/)
assert.match(pageSource, /titleTypeLabel/)
assert.match(pageSource, /titleUsageStateLabel/)
assert.match(pageSource, /row\.titleTypes/)
assert.match(pageSource, /row\.titleUsageStates/)
assert.match(pageSource, /row\.competitorEvidence/)
assert.match(pageSource, /row\.adsEvidence/)
assert.match(pageSource, /row\.negativeCandidate/)
assert.match(pageSource, /核心词/)
assert.match(pageSource, /属性词/)
assert.match(pageSource, /场景词/)
assert.match(pageSource, /人群词/)
assert.match(pageSource, /规格词/)
assert.match(pageSource, /流行词/)
assert.match(pageSource, /标题目标/)
assert.match(pageSource, /当前已覆盖/)
assert.match(pageSource, /当前未覆盖/)
assert.match(pageSource, /已从标题移除/)
assert.match(pageSource, /不适合标题/)
assert.match(pageSource, /有竞品证据/)
assert.match(pageSource, /无竞品证据/)
assert.match(pageSource, /有广告证据/)
assert.match(pageSource, /无广告证据/)
assert.match(pageSource, /否词候选/)
assert.doesNotMatch(pageSource, /状态 \/ 标签/)
assert.doesNotMatch(pageSource, /intentTagLabel/)
assert.doesNotMatch(pageSource, /titleCoverage\(parseTags\(row\.intentTagsJson\)\)/)
