import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const pageSource = readFileSync(join(process.cwd(), 'src/features/product-keywords/ProductKeywordDataPage.tsx'), 'utf8')

assert.match(pageSource, /data-testid="product-keyword-data-page"/)
assert.match(pageSource, /data-testid="product-keyword-table"/)
assert.match(pageSource, /const selectedStore = session\.currentStore/)
assert.match(pageSource, /titleTypeLabel/)
assert.match(pageSource, /titleUsageStateLabel/)
assert.match(pageSource, /row\.titleTypes/)
assert.match(pageSource, /row\.titleUsageStates/)
assert.match(pageSource, /row\.competitorEvidence/)
assert.match(pageSource, /row\.adsEvidence/)
assert.match(pageSource, /row\.negativeCandidate/)
assert.match(pageSource, /shouldShowKeywordNorm/)
assert.match(pageSource, /normalizedKeyword !== normalizedKeywordNorm/)
assert.match(pageSource, /shouldShowKeywordNorm\(row\) \? <Text type="secondary">\{row\.keywordNorm\}<\/Text> : null/)
assert.match(pageSource, /ProductKeywordHistoryDrawer/)
assert.match(pageSource, /HistoryOutlined/)
assert.match(pageSource, /selectedHistoryKeyword/)
assert.match(pageSource, /setSelectedHistoryKeyword\(row\)/)
assert.match(pageSource, /keywordNorm=\{selectedHistoryKeyword\?\.keywordNorm\}/)
assert.match(pageSource, /关键词历史：\$\{selectedHistoryKeyword\.keyword\}/)
assert.match(pageSource, />历史</)
assert.match(pageSource, /核心词/)
assert.match(pageSource, /属性词/)
assert.match(pageSource, /场景词/)
assert.match(pageSource, /人群词/)
assert.match(pageSource, /规格词/)
assert.match(pageSource, /流行词/)
assert.match(pageSource, /标题目标/)
assert.match(pageSource, /当前已覆盖/)
assert.match(pageSource, /当前未覆盖/)
assert.match(pageSource, /已从标题移除/)
assert.match(pageSource, /不适合标题/)
assert.match(pageSource, /有竞品证据/)
assert.match(pageSource, /无竞品证据/)
assert.match(pageSource, /有广告证据/)
assert.match(pageSource, /无广告证据/)
assert.match(pageSource, /否词候选/)
assert.doesNotMatch(pageSource, /data-testid="product-keyword-store-filter"/)
assert.doesNotMatch(pageSource, /selectedStoreKey/)
assert.doesNotMatch(pageSource, /setSelectedStoreKey/)
assert.doesNotMatch(pageSource, /uniqueStores/)
assert.doesNotMatch(pageSource, /storeLabel/)
assert.doesNotMatch(pageSource, /product-keyword-store-select/)
assert.doesNotMatch(pageSource, /product-keyword-header/)
assert.doesNotMatch(pageSource, /ReloadOutlined/)
assert.doesNotMatch(pageSource, /summary\.total/)
assert.doesNotMatch(pageSource, /刷新关键词数据/)
assert.doesNotMatch(pageSource, /状态 \/ 标签/)
assert.doesNotMatch(pageSource, /product-keyword-status-filter/)
assert.doesNotMatch(pageSource, /statusOptions/)
assert.doesNotMatch(pageSource, /StatusFilter/)
assert.doesNotMatch(pageSource, /statusLabel/)
assert.doesNotMatch(pageSource, /statusColor/)
assert.doesNotMatch(pageSource, /row\.status/)
assert.doesNotMatch(pageSource, /已纳入词库/)
assert.doesNotMatch(pageSource, /待确认候选/)
assert.doesNotMatch(pageSource, /已启用/)
assert.doesNotMatch(pageSource, /intentTagLabel/)
assert.doesNotMatch(pageSource, /titleCoverage\(parseTags\(row\.intentTagsJson\)\)/)
