import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()

function source(path: string) {
  return readFileSync(join(root, path), 'utf8')
}

const apiSource = source('src/features/product-keywords/api.ts')
const typesSource = source('src/features/product-keywords/types.ts')
const menuSource = source('src/features/app-shell/WorkspaceMenuRegistry.ts')
const lazySource = source('src/features/app-shell/ShellWorkspaceLazyComponents.tsx')
const contentSource = source('src/features/app-shell/ShellWorkspaceContent.tsx')
const routingSource = source('src/features/app-shell/WorkspaceRouting.ts')
const sessionSource = source('src/features/app-shell/ShellSessionStorage.ts')

assert.match(apiSource, /\/api\/product-keywords/)
assert.match(apiSource, /fetchProductKeywords/)
assert.match(apiSource, /fetchProductKeywordProduct/)
assert.match(apiSource, /addProductKeyword/)
assert.match(apiSource, /addProductCompetitorKeywords/)
assert.match(apiSource, /updateProductKeyword/)
assert.match(apiSource, /saveProductKeywordEditorChanges/)
assert.match(apiSource, /\/api\/product-keywords\/editor-save/)
assert.match(apiSource, /\/api\/product-keywords\/competitor-keywords/)
assert.match(apiSource, /appendParam\(search, 'keyword', params\.keywordNorm\)/)
assert.doesNotMatch(apiSource, /appendParam\(search, 'keywordNorm'/)
assert.match(typesSource, /ProductKeywordListRequest/)
assert.match(typesSource, /ProductKeywordCommand/)
assert.match(typesSource, /ProductCompetitorKeywordCommand/)
assert.match(typesSource, /ProductKeywordEditorSaveCommand/)
assert.match(typesSource, /keywords: string\[\]/)
assert.match(typesSource, /competitorSources\?: ProductCompetitorKeywordSource\[\]/)
assert.match(typesSource, /sourceText\?: string/)
assert.match(typesSource, /titleTypes/)
assert.match(typesSource, /titleUsageStates/)
assert.match(typesSource, /competitorEvidence/)
assert.match(typesSource, /adsEvidence/)
assert.match(typesSource, /negativeCandidate/)
assert.match(menuSource, /'operations-product-keywords'/)
assert.match(menuSource, /\/operations\/product-keywords/)
assert.match(lazySource, /ProductKeywordDataPage/)
assert.match(contentSource, /ProductKeywordDataPage/)
assert.match(routingSource, /OPERATIONS_PRODUCT_KEYWORDS_PATH/)
assert.match(sessionSource, /OPERATIONS_PRODUCT_KEYWORDS_PATH/)
assert.match(sessionSource, /search\.get\('grantProductKeywords'\)/)
assert.match(sessionSource, /menuId:\s*9804/)
assert.match(sessionSource, /menuName:\s*'关键词数据'/)
