import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const listCellSource = readFileSync(
  join(root, 'src/features/product-management/components/ProductListIdentityCells.tsx'),
  'utf8'
)
const hoverSource = readFileSync(join(root, 'src/features/product-keywords/ProductKeywordListHoverPopover.tsx'), 'utf8')

assert.match(listCellSource, /ProductKeywordListHoverPopover/)
assert.match(listCellSource, /partnerSku=\{record\.partnerSku\}/)
assert.match(hoverSource, /Popover/)
assert.match(hoverSource, /fetchProductKeywordProduct/)
assert.match(hoverSource, /onOpenChange/)
assert.match(hoverSource, /data-testid="product-keyword-list-hover"/)
assert.match(hoverSource, /const label = '关键词'/)
assert.doesNotMatch(hoverSource, /关键词 \$\{panel\.keywords\.length\}/)
assert.match(hoverSource, /function titleTypeLabel/)
assert.match(hoverSource, /function titleUsageStateLabel/)
assert.match(hoverSource, /keyword\.titleTypes/)
assert.match(hoverSource, /keyword\.titleUsageStates/)
assert.match(hoverSource, /keyword\.competitorEvidence/)
assert.match(hoverSource, /keyword\.adsEvidence/)
assert.match(hoverSource, /keyword\.negativeCandidate/)
assert.match(hoverSource, /核心词/)
assert.match(hoverSource, /流行词/)
assert.match(hoverSource, /标题目标/)
assert.match(hoverSource, /有竞品证据/)
assert.match(hoverSource, /有广告证据/)
assert.match(hoverSource, /否词候选/)
assert.doesNotMatch(hoverSource, /keywordStatusLabel/)
assert.doesNotMatch(hoverSource, /keywordStatusColor/)
assert.doesNotMatch(hoverSource, /keyword\.status/)
assert.doesNotMatch(hoverSource, /已纳入词库/)
assert.doesNotMatch(hoverSource, /待确认候选/)
assert.doesNotMatch(hoverSource, /keywordIntentLabel/)
assert.doesNotMatch(hoverSource, /已启用/)
assert.doesNotMatch(hoverSource, /竞品跟踪词/)
assert.doesNotMatch(hoverSource, /广告搜索词/)
assert.doesNotMatch(hoverSource, /标题使用 \{counts\.title\}/)
assert.doesNotMatch(hoverSource, /竞品证据 \{counts\.competitor\}/)
assert.doesNotMatch(hoverSource, /广告搜索 \{counts\.ads\}/)
assert.match(hoverSource, /TITLE_HISTORY/)
assert.match(hoverSource, /COMPETITOR_KEYWORD/)
assert.match(hoverSource, /ADS_QUERY/)
