export * from './productDetailAdapterTypes'
export * from './productDetailAdapterDraft'
export * from './productDetailAdapterSnapshot'
export * from './productDetailAdapterDomains'
export { normalizeProductListingImageRoleAssignments, normalizeProductListingKeyAttributes } from './productDetailAdapterNormalization'
